### ISSUE TITLE
Mislim da so relacije na desni strani enacaja pomesane

### ISSUE THREAD

**Issue by DordeK** [mkrnc/TOR1-zapiski-s-predavanj#1]
https://github.com/mkrnc/TOR1-zapiski-s-predavanj/blob/28f0ad23c22b0a31c67e71408a9361797a2822df/TOR1.tex#L3443

**Comment by herbiehp** [comment]
smiselno je vedni napisati kje tocno in kaj je predlog popravka

**Comment by herbiehp** [comment]
source line 3440 - 3442:
 $R_=^{-1}~~=~~R_=\,,$

$R_{\neq}^{-1}~~=~~R_{\neq}\,.$

A copy/paste problem?

**Comment by mkrnc** [comment]
Thank you, @DordeK , for raising this issue.
Indeed; the problem was resolved by latest commit by @herbiehp 
So I close this issue now.
